# introducing the most idiotic way to generate html, but for now and in our case this works. In a professional even corperate enviroment you would not use this 
# it would actually be best to throw this into an array, parse the array, make a do loop and go from there and write the data to the file. But this was quicker for testing
module Loader 
    class Template 
        def fill_simple_Template(x : String)
            tmpl = "HTML/main.html"
            File.open(tmpl, "w") do |f|
                f.print "<!-- This file was generated by the server, do not remove this file unless youa re a developer -->"
                f.print "<!DOCTYPE html>"
                f.print "<html lang='en'>"
                f.print "<head>"
                f.print "<meta charset='UTF-8'>" 
                f.print "<meta http-equiv='X-UA-Compatible' content='IE=edge'>"
                f.print "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
                f.print "<title>Pre generated template</title>"
                f.print "</head>"
                f.print "<body>"
                f.print "<div>"
                f.print "<p> #{x} </p>"
                f.print "</div>"
                f.print "</body>"
                f.print "</html>"
            end
        end
    end
end
